export const FORM_CONSTANTS = {
  FIRST_NAME: "firstName",
  LAST_NAME: "lastName",
  EMAIL: "email",
  PHONE: "phone",
  STREET: "street",
  UNIT: "unit",
  CITY: "city",
  STATE: "state",
  ZIP: "zip",
  PRODUCT_A: "productA",
  PRODUCT_B: "productB",
  PRODUCT_C: "productC",
}

export const REQUIRED_FORM_FIELDS = [
  FORM_CONSTANTS.FIRST_NAME,
  FORM_CONSTANTS.LAST_NAME,
  FORM_CONSTANTS.EMAIL,
  FORM_CONSTANTS.PHONE,
  FORM_CONSTANTS.STREET,
  FORM_CONSTANTS.CITY,
  FORM_CONSTANTS.STATE,
  FORM_CONSTANTS.ZIP,
  [FORM_CONSTANTS.PRODUCT_A, FORM_CONSTANTS.PRODUCT_B, FORM_CONSTANTS.PRODUCT_C]
]

export const States = [
  'alabama',        'alaska',         'arizona',
  'arkansas',       'california',     'colorado',
  'connecticut',    'delaware',       'district of columbia',
  'florida',        'georgia',        'hawaii',
  'idaho',          'illinois',       'indiana',
  'iowa',           'kansas',         'kentucky',
  'louisiana',      'maine',          'maryland',
  'massachusetts',  'michigan',       'minnesota',
  'mississippi',    'missouri',       'montana',
  'nebraska',       'nevada',         'new hampshire',
  'new jersey',     'new mexico',     'new york',
  'north carolina', 'north dakota',   'ohio',
  'oklahoma',       'oregon',         'pennsylvania',
  'rhode island',   'south carolina', 'south dakota',
  'tennessee',      'texas',          'utah',
  'vermont',        'virgin islands', 'virginia',
  'washington',     'west virginia',  'wisconsin',
  'wyoming'
]

export const STATES_ABBREVIATED = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District Of Columbia",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VI: "Virgin Islands",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming"
}
