import { FORM_CONSTANTS } from '../../../constants'

export default {
  [FORM_CONSTANTS.FIRST_NAME]: "",
  [FORM_CONSTANTS.LAST_NAME]: "",
  [FORM_CONSTANTS.EMAIL]: "",
  [FORM_CONSTANTS.PHONE]: "",
  [FORM_CONSTANTS.STREET]: "",
  [FORM_CONSTANTS.UNIT]: "",
  [FORM_CONSTANTS.CITY]: "",
  [FORM_CONSTANTS.STATE]: "",
  [FORM_CONSTANTS.ZIP]: "",
  [FORM_CONSTANTS.PRODUCTS]: []
}
